### ISSUE TITLE
Update todo routes to work for our posts

### ISSUE THREAD

**Issue by shenando** [flannel-mouths/only-fish#11]
We have a todo route left over from the old code. We need to update it to make sure the routes are up to date and working with the new posts we are integrating into the project.

**Comment by geosheehan** [comment]
This is mostly done in this commit:
https://github.com/flannel-mouths/only-fish/commit/ede4e90854edf05a75c20746a681ef448348562c

TODO:
 - Add authentication to routes
 - Add additional features as time permits

**Comment by geosheehan** [comment]
Remaining tasks have been split into new issues.
